# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "imgui_cmkr"

[variables]
GLFW_BUILD_DOCS = false
GLFW_INSTALL = false

[subdir.glfw]

[target.imgui]
type = "static"
include-directories = [
    "imgui",
    "imgui/backends",
    #"imgui/examples/libs/glfw/include",
]
sources = [
    "imgui/*.cpp",
    "imgui/*.h",
    "imgui/backends/imgui_impl_opengl3.cpp",
    "imgui/backends/imgui_impl_opengl3.h",
    "imgui/backends/imgui_impl_opengl3_loader.h",
    "imgui/backends/imgui_impl_glfw.cpp",
    "imgui/backends/imgui_impl_glfw.h",
]
windows.sources = [
    "imgui/backends/imgui_impl_win32.cpp",
    "imgui/backends/imgui_impl_win32.h",
]
link-libraries = ["glfw"]
clang.compile-options = ["-fsanitize"]

[target.imgui_cmkr]
type = "executable"
sources = [
    "src/main.cpp",
    "src/ui.cpp",
    "src/ui.h",
]
compile-features = ["cxx_std_11"]
link-libraries = ["imgui"]